message:
  no-perms: "&6InstaMine &7» &cYou don't have required permissions to run this command."
  no-args: "&6InstaMine &7» &cYou have to provide arguments to run this command."
  unknown-arg: "&6InstaMine &7» &cProvided argument does not exist."
  reloaded: "&6InstaMine &7» &aPlugin was reloaded successfully."
